// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLwPw2NrfwcPQWgsiOEfNOQYzGoO8NnoQ',
    appId: '1:1087977239434:web:ddf8ebb4c73531b744ce73',
    messagingSenderId: '1087977239434',
    projectId: 'eccommerce-7918a',
    authDomain: 'eccommerce-7918a.firebaseapp.com',
    storageBucket: 'eccommerce-7918a.appspot.com',
    measurementId: 'G-QSLC1LX4R2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQAri9iZD9A3VMsurR3giRIyvXuoYABI0',
    appId: '1:1087977239434:ios:1cd3c5a3e5903a6f44ce73',
    messagingSenderId: '1087977239434',
    projectId: 'eccommerce-7918a',
    storageBucket: 'eccommerce-7918a.appspot.com',
    iosBundleId: 'com.example.practiceImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQAri9iZD9A3VMsurR3giRIyvXuoYABI0',
    appId: '1:1087977239434:ios:1cd3c5a3e5903a6f44ce73',
    messagingSenderId: '1087977239434',
    projectId: 'eccommerce-7918a',
    storageBucket: 'eccommerce-7918a.appspot.com',
    iosBundleId: 'com.example.practiceImage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLwPw2NrfwcPQWgsiOEfNOQYzGoO8NnoQ',
    appId: '1:1087977239434:web:d2d27cd59bc2b26d44ce73',
    messagingSenderId: '1087977239434',
    projectId: 'eccommerce-7918a',
    authDomain: 'eccommerce-7918a.firebaseapp.com',
    storageBucket: 'eccommerce-7918a.appspot.com',
    measurementId: 'G-PM7JK886X2',
  );

}