// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7LnYXbO4fIP6g9k3IKnDwZXH01UZPelw',
    appId: '1:28638115933:web:363c8c3cf6911bf7a035b4',
    messagingSenderId: '28638115933',
    projectId: 'quickmedicalapp',
    authDomain: 'quickmedicalapp.firebaseapp.com',
    storageBucket: 'quickmedicalapp.appspot.com',
    measurementId: 'G-XJJLS02968',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClro-0OhKasU1qfAZaj5c3dSs7ciXX0YQ',
    appId: '1:28638115933:android:c0ccf686b7eb1271a035b4',
    messagingSenderId: '28638115933',
    projectId: 'quickmedicalapp',
    storageBucket: 'quickmedicalapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHaXcrhelJOzIi0hjfrJQlpHp4QWJ7Rw',
    appId: '1:28638115933:ios:1775c8347c037bd7a035b4',
    messagingSenderId: '28638115933',
    projectId: 'quickmedicalapp',
    storageBucket: 'quickmedicalapp.appspot.com',
    iosBundleId: 'com.example.practiceImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnHaXcrhelJOzIi0hjfrJQlpHp4QWJ7Rw',
    appId: '1:28638115933:ios:1775c8347c037bd7a035b4',
    messagingSenderId: '28638115933',
    projectId: 'quickmedicalapp',
    storageBucket: 'quickmedicalapp.appspot.com',
    iosBundleId: 'com.example.practiceImage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7LnYXbO4fIP6g9k3IKnDwZXH01UZPelw',
    appId: '1:28638115933:web:aca842babcfc12efa035b4',
    messagingSenderId: '28638115933',
    projectId: 'quickmedicalapp',
    authDomain: 'quickmedicalapp.firebaseapp.com',
    storageBucket: 'quickmedicalapp.appspot.com',
    measurementId: 'G-LGXVT48LVL',
  );
}
